/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DataStorage {
	/**
	 * the ID of the current match.
	 */
	currentMatchId: number;
	/**
	 * the ID of the next match to be created
	 */
	nextMatchId: number;
	/**
	 * the ID of the next team to be created
	 */
	nextTeamId: number;
	streamTitle?: string;
	randomisationKey?: number;
}
