/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Team } from "../Team";
/**
 * Team Replicant
 */
export interface TeamReplicant {
	/**
	 * an array of teams.
	 */
	teams: Team[];
	[k: string]: unknown;
}
