/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Map Lineup
 */
export interface MapLineup {
  /**
   * best of/first to maps
   */
  scoreaim: number;
  /**
   * best of or first to
   */
  scoringType: "ft" | "bo";
  /**
   * the selection of maps
   */
  maps: MapSelection[];
  [k: string]: unknown;
}
