/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Map Option
 */
export interface MapSelection {
  /**
   * the selected map
   */
  selectedMap?: string;
  /**
   * a list of potential maps
   */
  potentialMaps?: string[];
  [k: string]: unknown;
}
