/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Team } from "./Team";
import { MapLineup } from "./MapLineup";
import { TextBar } from "./TextBar";

/**
 * A match
 */
export interface MatchData {
	/**
	 * Unique match ID
	 */
	matchId: number;

	/**
	 * the id of team 1. may be null if no team has been set.
	 */
	team1id?: number;
	/**
	 * the id of team 2. may be null if no team has been set.
	 */
	team2id?: number;
	/**
	 * match information. may be null if no information has been set.
	 */
	information?: string;
	/**
	 * team 1 score
	 */
	team1score: number;
	/**
	 * team 1 score
	 */
	team2score: number;
	/**
	 * do we flip the teams display?
	 */
	flipped: boolean;
	/**
	 * is the match considered completed?
	 */
	completed: boolean;
	mapLineup?: MapLineup;

	/**
	 * has this match been marked for deletion
	 */
	deleted?: boolean;

	/**
	 * text that gets rotated through on the top bar
	 */
	textBars: TextBar[];
}
