/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { Player } from "./Player";

/**
 * A Team
 */
export interface Team {
	/**
	 * team id, unique
	 */
	teamId: number;
	/**
	 * team name
	 */
	name: string;
	/**
	 * players on the team
	 */
	players: Player[];
	/**
	 * icons related to the team
	 */
	icons?: {
		/**
		 * url of the teams icon
		 */
		teamIcon?: string;
		[k: string]: unknown;
	};
	/**
	 * colours related to the team
	 */
	colors: {
		/**
		 * primary team color
		 */
		primary?: string;
		/**
		 * text color
		 */
		textColor?: string;
		/**
		 * team player color
		 */
		player?: string;
		/**
		 * team shadow color
		 */
		shadow?: string;
		[k: string]: unknown;
	};
	[k: string]: unknown;
}
